### ISSUE TITLE
To do list

### ISSUE THREAD

**Issue by ryanmartinneutrino** [Queens-Physics/qexpy#14]
- Need to add a bokeh histogram function to plotting, and clean up the code in error.py
- Should add a list that goes with the datasets in plotting that gives the index of which of their fit functions to display 
- Check if error bands are properly calculated with derivative method, in particular if a partial derivative is zero, that parameter may not contribute. -> should we just use MC for the error band? But then we have to be sure that the correlations are done properly.
- Plot and fitting is unstable if the values on x-axis are very small (works fine if they are all scaled up), probably the error scipy.optimize. Should also check the padding on the axes when the values are small. 
- The fit function of a dataset should provide an opportunity to give the function a name

**Comment by astralcai** [comment]
outdated
