### ISSUE TITLE
qexpy.error.Measurement does not recognize lists of values with their corresponding uncertainties

### ISSUE THREAD

**Issue by ReckoningReckoner** [Queens-Physics/qexpy#26]
In the [documentation](http://qexpy.readthedocs.io/en/latest/uncertainties.html), the following example is given:

`y = e.Measurement([10, 9, 11], [1, 0.5, 0.25])`

If I try to run that code, I get the following TypeError:
`TypeError: Input must be either a single array of values,
                      or the central value and uncertainty in one measurement`

Looking at the [code](https://github.com/Queens-Physics/qexpy/blob/master/qexpy/error.py#L35), I've noticed that the if statement will always throw a `TypeError` if the two args aren't of a [qexpy.utils.number_types](https://github.com/Queens-Physics/qexpy/blob/master/qexpy/utils.py#L23). I think the documentation should be changed to reflect the fact that this feature is not implemented in the official release.

Note: I have installed qexpy by using pip3

**Comment by ryanmartinneutrino** [comment]
Hi Viraj,
Thanks for the comment. Yes, the documentation on readthedocs is hopelessly
out of date. The most current resource for documentation is the example
notebooks in:

https://github.com/Queens-Physics/qexpy/tree/master/examples/jupyter

For your specific use-case, you want to use a MeasurementArray (as shown in
the first example notebook).

Cheers,
Ryan.

**Comment by ReckoningReckoner** [comment]
Thanks for the quick response. I'll be sure to use the newer documentation. FYI I've created a pull request https://github.com/Queens-Physics/qexpy/pull/27 with a brief message explaining the deprecated feature. Up to you if you think it will be useful.
