### ISSUE TITLE
Add ability to concatenate MeasurementArray

### ISSUE THREAD

**Issue by ryanmartinneutrino** [Queens-Physics/qexpy#39]
Generally works, but doesn't know how to print... For example:

import numpy as np
arr = q.MeasurementArray([(1,0.1),(2,0.2)])
bar = q.MeasurementArray([(3,0.3),(4,0.4)])
arr = np.concatenate((arr,bar))
carr = 2*arr
print(carr)

**Comment by astralcai** [comment]
This is interesting. I can look into how to make these numpy functions work with MeasurementArrays over the summer. Keep this one.

**Comment by astralcai** [comment]
MeasurementArray comes with its own function to concatenate with another array
