### ISSUE TITLE
Functions to get chi2, ndof, and prob after a fit

### ISSUE THREAD

**Issue by ryanmartinneutrino** [Queens-Physics/qexpy#46]
Currently, it's cumbersome to extract the result of a fit:
```
fig.datasets[0].fit_chi2[0]
fig.datasets[0].fit_ndof[0]
```

**Comment by astralcai** [comment]
This is implemented in the new version (the fit function returns a fit result object that contains all these information)

https://qexpy.readthedocs.io/en/latest/fitting.html
