### ISSUE TITLE
N/kg is not correctly identified as m/s**2. kg*m/s**2 is not accepted as a unit. 

### ISSUE THREAD

**Issue by skellig18** [Queens-Physics/qexpy#51]
The flagging for units being incorrect does not seem to properly divide units involving Newtons. I get the warning:

/home/[username]/.local/lib/python3.6/site-packages/qexpy/utils/units.py:277: UserWarning: You're trying to add/subtract two values with mismatching units.

**Comment by astralcai** [comment]
1. The package at this point does not support interpreting N as kg*m/s^2. This is an interesting feature request. I will add it to my to-do list.

2. The exponent should be typed as "^" instead of "**"

**Comment by astralcai** [comment]
This feature has been added
