### ISSUE TITLE
Fitting errors don't scale with data errors

### ISSUE THREAD

**Issue by ryanmartinneutrino** [Queens-Physics/qexpy#57]
When using the fitting module, the uncertainties on the fit parameters do not seem to scale with the uncertainties on the data points. I think this would be resolved by adding `absolute_sigma = True` in the call to `scipy.optimize.curve_fit()`

**Comment by astralcai** [comment]
Fixed and published to Pypi

**Comment by astralcai** [comment]
@ryanmartinneutrino 

I'm having second thoughts over this change. The `scipy.optimize` module has the `absolute_sigma` term set to `False` by default for a reason, and when I read the documentation of [scipy.optimize.curve_fit](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.curve_fit.html), it suggests that the two uncertainties are off by a scaling factor that has to do with the goodness of fit (chi2/ndof). Specifically, the `scipy` documentation states that
> ```pcov(absolute_sigma=False) = pcov(absolute_sigma=True) * chisq(popt)/(M-N)```

I still don't quite understand what the difference is conceptually. Would you be able to elaborate? I'm trying to justify adding this somewhat "unexpected" behaviour to our `fitting` module, as when users try to compare results of our fit vs. results they obtain themselves with `scipy`, they might see different uncertainty estimates for the fit parameters, and they might not be able to figure out why.

**Comment by ryanmartinneutrino** [comment]
That is a good point. To be honest, I don't fully understand why scipy optimize set it the other way by default, but it's not the behaviour that a physicist would expect. We expect that if the uncertainty in the data are larger, then the uncertainties on the fit parameters should be larger as well. I think keeping the update (`absolute_sigma=True`) is the right thing to do as we're targeting this at physics labs and the default in qexpy should be the common sense expectation of a physicist. 

It is disturbing that those using scipy directly will be confused by their results, but hopefully that prompts them to realize they're likely using scipy incorrectly! What if instead we print out some sort of warning that highlights that this will be different than scipy's curve_fit?

**Comment by astralcai** [comment]
> That is a good point. To be honest, I don't fully understand why scipy optimize set it the other way by default, but it's not the behaviour that a physicist would expect. We expect that if the uncertainty in the data are larger, then the uncertainties on the fit parameters should be larger as well. I think keeping the update (`absolute_sigma=True`) is the right thing to do as we're targeting this at physics labs and the default in qexpy should be the common sense expectation of a physicist.
> 
> It is disturbing that those using scipy directly will be confused by their results, but hopefully that prompts them to realize they're likely using scipy incorrectly! What if instead we print out some sort of warning that highlights that this will be different than scipy's curve_fit?

I don't think a warning would be necessary. As long as we can confirm that this behaviour is indeed expected for our purposes, there is no need to explicitly warn people about our library producing a slightly different result from another library.
